global:
  scrape_interval:     1s

scrape_configs:
- job_name: prometheus
  metrics_path: /prometheus/metrics
  static_configs:
  - targets:
    - localhost:9090
- job_name: go_demo
  metrics_path: /metrics
  static_configs:
  - targets:
    - "go-demo-svc:8080"
  metric_relabel_configs:
  - source_labels: ['group']
    regex: .*__pdname__(.*)
    target_label: 'service'
  - source_labels: ['group']
    regex: (.*)__pdname__.*
    target_label: 'group'

rule_files:
- /etc/config/testalert.yml

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager-svc:9093"
