---

global:
    pagerduty_url: "https://events.pagerduty.com/v2/enqueue"

route:
  group_by: ['alertname', 'job']
  group_interval: 10s
  group_wait: 10s
  repeat_interval: 600s
  receiver: sre-pager
  routes:
  - match:
      alertname: TestAlert
    routes:
    - match:
        service: test_service
      receiver: sre-pager
receivers:
- name: 'sre-pager'
  pagerduty_configs:
  - service_key: $PAGERKEY
